# Generated by Django 5.0.7 on 2024-07-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="servico_efetuados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_do_cliente", models.CharField(max_length=100)),
                ("serviço", models.CharField(max_length=100)),
                ("valor_cobrado", models.IntegerField()),
                ("pagamento", models.IntegerField()),
            ],
        ),
    ]
