# Generated by Django 5.0.7 on 2024-07-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("negocio", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="servico_efetuados",
            old_name="serviço",
            new_name="servico",
        ),
        migrations.AlterField(
            model_name="servico_efetuados",
            name="pagamento",
            field=models.CharField(max_length=100),
        ),
    ]
