# Generated by Django 5.0.7 on 2024-07-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("negocio", "0002_rename_serviço_servico_efetuados_servico_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="servicos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_do_cliente", models.CharField(max_length=100)),
                ("servico", models.CharField(max_length=100)),
                ("valor_cobrado", models.IntegerField()),
                ("pagamento", models.CharField(max_length=100)),
                ("cemiterio", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="servico_efetuados",
        ),
    ]
